databases:
  - name: blue_velvet_coffee
    user: blue_velvet_coffee
    plan: free
    region: oregon

services:
  - type: web
    name: blue_velvet_coffee
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blue_velvet_coffee
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
        